### ISSUE TITLE
Telldus device

### ISSUE THREAD

**Issue by bohtho** [perbrage/node-red-contrib-telldus-zwave-v2-local#2]
(Hi again!:))

I am in the process of getting a combo device like the Telldus devices, but can't seem to find one called "Telldus Zwave v2". As you state: 

> "These nodes might work for other Telldus gateway devices, but that has not been confirmed"

which device exactly is it you have confirmed the nodes with as I might purchase exactly that in case ? Is it the "Telldus Znet Lite v2"?

**Comment by perbrage** [comment]
Yes, it is indeed the Telldus Znet Lite v2. Here is a link: https://www.dustinhome.se/product/5010996577/znet-lite-v2

This is the one I use and test with. Works like a charm for controlling lamps on/of when arming/disarming using the check functionality of the sector alarm node :)

**Comment by bohtho** [comment]
Very cool. I like the combination of two radios in one. And love to keep trying to cram all my HA into node-red only (including alarm systems;)).
