### ISSUE TITLE
fails to configure/install

### ISSUE THREAD

**Issue by ebcjaa** [perbrage/node-red-contrib-telldus-zwave-v2-local#5]
Seems to install ok, but...
configuring gateway with wizzard does not work, nothing happens when pressing the spyglass icon.
manual configurations seems to work

when depolying node-red: Flows stopped due to missing node types.
telldus-gateway
telldus-device

log from install:
Aug  5 08:56:40 raspberrypi Node-RED[1654]: 5 Aug 08:56:40 - [info] Installing module: node-red-contrib-telldus-zwave-v2-local, version: 1.3.4
Aug  5 08:56:40 raspberrypi Node-RED[1654]: 5 Aug 08:56:40 - [trace] npm["install","--save","--save-prefix=\"~\"","--production","node-red-contrib-telldus-zwave-v2-local@1.3.4"]
Aug  5 08:57:10 raspberrypi Node-RED[1654]: 5 Aug 08:57:10 - [info] Installed module: node-red-contrib-telldus-zwave-v2-local
Aug  5 08:57:11 raspberrypi Node-RED[1654]: 5 Aug 08:57:11 - [info] Added node types:
Aug  5 08:57:11 raspberrypi Node-RED[1654]: 5 Aug 08:57:11 - [info]  - node-red-contrib-telldus-zwave-v2-local:telldus-gateway : SyntaxError: missing ) after argument list
Aug  5 08:57:11 raspberrypi Node-RED[1654]: 5 Aug 08:57:11 - [info]  - node-red-contrib-telldus-zwave-v2-local:telldus-device : SyntaxError: missing ) after argument list
Aug  5 08:57:11 raspberrypi Node-RED[1654]: 5 Aug 08:57:11 - [info]  - node-red-contrib-telldus-zwave-v2-local:telldus-metricsensor : SyntaxError: Unexpected token function
Aug  5 08:57:11 raspberrypi Node-RED[1654]: 5 Aug 08:57:11 - [info]  - node-red-contrib-telldus-zwave-v2-local:telldus-switchsensor : SyntaxError: Unexpected token function

Manage pallet shows the node-red-contrib-telldus-zwave-v2-local, last object with a red exklamation mark!

nodes depreciated after restart:
5 Aug 10:21:15 - [info] Node-RED version: v0.18.7
5 Aug 10:21:15 - [info] Node.js  version: v6.14.2
5 Aug 10:21:15 - [info] Linux 4.14.34-v7+ arm LE
5 Aug 10:21:16 - [info] Loading palette nodes
5 Aug 10:21:26 - [info] Dashboard up and running
5 Aug 10:21:30 - [info] Dashboard version 2.6.2 started at /ui
5 Aug 10:21:32 - [warn] ------------------------------------------------------
5 Aug 10:21:32 - [warn] [node-red-contrib-telldus-zwave-v2-local/telldus-gateway] SyntaxError: missing ) after argument list
5 Aug 10:21:32 - [warn] [node-red-contrib-telldus-zwave-v2-local/telldus-device] SyntaxError: missing ) after argument list
5 Aug 10:21:32 - [warn] [node-red-contrib-telldus-zwave-v2-local/telldus-metricsensor] SyntaxError: Unexpected token function
5 Aug 10:21:32 - [warn] [node-red-contrib-telldus-zwave-v2-local/telldus-switchsensor] SyntaxError: Unexpected token function
5 Aug 10:21:32 - [warn] ------------------------------------------------------

I also have "node telldus live" and "node-red-contrib-tellstick" could there be a conflict?

**Comment by perbrage** [comment]
Been seeing weird errors from people using old node versions. Take the appropriate steps to upgrade your node version and try again.

**Comment by ebcjaa** [comment]
Works fine with Node.js  version: v8.11.3, Thanks!
