### ISSUE TITLE
dim-function

### ISSUE THREAD

**Issue by hnrk** [perbrage/node-red-contrib-telldus-zwave-v2-local#7]
This node doesn't seem to support dimming. Or am I missing something?

**Comment by perbrage** [comment]
You are correct! It does not currently support dimming as I don't have any device that supports dimming currently. So I have no way of testing it. 

It is quite easily to implemented however.

**Comment by perbrage** [comment]
Just published a new version to support dimming, try version 1.3.5 and use the command dim(10) or dim(90) or similar.

Let me know if it works, cause I have no way of testing it.

**Comment by hnrk** [comment]
Solved! It works! That was quick. ;-)

**Comment by perbrage** [comment]
Great! Was such an easy thing to do, so I thought I'd just do it. Closing this issue shortly!
