### ISSUE TITLE
support for 433 devices?

### ISSUE THREAD

**Issue by svefro** [perbrage/node-red-contrib-telldus-zwave-v2-local#8]
I can't seem to find any devices in "switch-sensor" node.
Are 433 devices supported?

i don't have any z-wave devices

**Comment by perbrage** [comment]
Switch sensors are for on/off devices such as a motion detector, while the metric sensor node is for scales such as temperatures, UV level etc.

I don't have any 433 devices, but if they are exposed by the telldus local API (meaning they have a local id), I suppose they should work.

FYI, the dropdowns the nodes provide is not mandatory to select. If you find you device local ID, you can enter it manually instead.

**Comment by svefro** [comment]
Got it working now.
i had the wrong id. i found the id at live.telldus.com under "Enhetskode" but that was wrong.  found the right id using a device node and pressing search, then copy paste that id in to "switch-sensor"

Are you planning on making more node's for node red?

it would be nice with a device list node that could output all devices and sensors with id and then a request node to read all parameters from each device.

That way a interface could be generated dynamically.
it would also be nice to be able to set "device id" in the device node from the msg object.
Then only one device node is needed for all devices.

I bought my TellStick ZNet Lite v2 yesterday so i'm quite new with the api.
i would like to be able to control and read all data from the tellstick locally from node-red.

-Svein

**Comment by perbrage** [comment]
Great that you got it working. Also thank you for the suggestions and input! I will give it some thought when I have time and get back to you!

**Comment by svefro** [comment]
I returned my telldus to the store since i was not happy with it.
Bought a rfxcom433xl instead. that works great.
